name: Create release

on:
  workflow_dispatch:
    inputs:
      runId:
        description: 'Build workflow run ID'
        required: true
      releaseVersion:
        description: 'Release version'
        required: true
      regions:
        description: 'Comma separated list of regions'
        required: true
jobs:
  createRelease:
    name: Download artifact and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get run details
        id: get_run_details
        run: |
          token=${{ secrets.GITHUB_TOKEN }}
          runId=${{ github.events.inputs.runId }}
          releaseVersion=${{ github.events.inputs.releaseVersion }}

          # API URLs
          run_details_url="https://api.github.com/repos/kapslocker/nli/actions/runs/$runId"
          artifact_details_url="https://api.github.com/repos/kapslocker/nli/actions/$runId/artifacts"

          # Get run details and artifact information
          run_details=$(curl -H "Authorization: token $token" -L $run_details_url)
          artifact_details=$(curl -H "Authorization: token $token" -L $artifact_details_url)

          echo $run_details
          # get branch name
          head_branch=$(echo $run_details | python3 -c "import sys, json; print(json.load(sys.stdin)['head_branch'])")
          base_version=$releaseVersion

          # Get the substring after the last slash /
          branch_version=${head_branch##*/}
          run_number=$(echo $run_details | python3 -c "import sys, json; print(json.load(sys.stdin)['run_number'])")

          # Join all components and prepare version number
          function join_by { local IFS="$1"; shift; echo "$*"; }
          version=$(join_by . $base_version $branch_version $run_number)

          # Download wheel
          artifact_url=$(echo $artifact_details | python -c "import sys, json; print([i['archive_download_url'] for i in json.load(sys.stdin)['artifacts'] if i['name'] == 'treewhl'][0])")
          curl -H "Authorization: token $token" -L $artifact_url -o ../treewhl.zip

          # Return the version number for usage in future steps
          echo "::set-output name=version::$version"
