name: Create release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true

jobs:
  buildExtension:
    name: Build extension and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build extension
        id: build_extension
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          ref="${{ github.ref }}"
          echo "ref is $ref"
          runNumber="${{ github.run_number }}"
          branch=${ref:11}
          branch_ver=${branch##*/}
          base_version=${{ github.event.inputs.tagName }}
          version="$base_version.$branch_ver.$runNumber"
          echo "Creating version $version"
           
