name: Build extension

on:
  push:
    branches:
      - master
      - releases/**

jobs:
  build:
    name: Build extension
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Build extension
        run: |
          cd tree-env
          python setup.py bdist_wheel -d ./
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: aidlswhl
          path: tree-env/*.whl
